keys:
  - &admin_maren         age1jtc7rzfsptrkdju6gtkxnx3r58wwym84ev04p4y2wxyv9tzslg6sy0ccqd
  - &admin_gavin         age1527ar0vl6ut69m5g0fff8wkl3dpytueukauejxavdqpl9d698vaseyf8sw
  - &server_monolith_dev age1d0fm822vy4ukfnyw54p6yyleanvplar60s3jkklt4el400tkqgqshkjttq
  - &server_monolith     age1xcpk4f97ltdcqy7yzudv4nsk3k00w5flkvlpap6c0leerh086gjqjza48y
creation_rules:
  # dev.env: decryptable by admins + dev server
  - path_regex: env/secrets/dev\.env$
    key_groups:
      - age:
        - *admin_maren
        - *admin_gavin
        - *server_monolith_dev
  # prod.env: decryptable by admins + prod server
  - path_regex: env/secrets/prod\.env$
    key_groups:
      - age:
        - *admin_maren
        - *admin_gavin
        - *server_monolith
