// Local development defaults.
// In production this file is generated by the NixOS module and served by nginx,
// overriding these values with the correct per-environment configuration.
window.FISHTANK_CONFIG = {
  serverUrl: 'http://localhost:3000',
  auth0Domain: 'your-tenant.eu.auth0.com',
  auth0ClientId: 'YOUR_AUTH0_CLIENT_ID',
};
